package com.haroun.bugoverflow.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PerfilUsuarioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerfilUsuarioAllPropertiesEquals(PerfilUsuario expected, PerfilUsuario actual) {
        assertPerfilUsuarioAutoGeneratedPropertiesEquals(expected, actual);
        assertPerfilUsuarioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerfilUsuarioAllUpdatablePropertiesEquals(PerfilUsuario expected, PerfilUsuario actual) {
        assertPerfilUsuarioUpdatableFieldsEquals(expected, actual);
        assertPerfilUsuarioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the derived primary key is set correctly.
     *
     * @param entityToPersist the entity used to persist
     * @param persisted the persisted entity
     */
    public static void assertPerfilUsuarioMapsIdRelationshipPersistedValue(PerfilUsuario entityToPersist, PerfilUsuario persisted) {
        // Validate the id for MapsId, the ids must be same
        assertThat(entityToPersist.getUser().getId()).isEqualTo(persisted.getId());
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerfilUsuarioAutoGeneratedPropertiesEquals(PerfilUsuario expected, PerfilUsuario actual) {
        assertThat(actual)
            .as("Verify PerfilUsuario auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerfilUsuarioUpdatableFieldsEquals(PerfilUsuario expected, PerfilUsuario actual) {
        assertThat(actual)
            .as("Verify PerfilUsuario relevant properties")
            .satisfies(a -> assertThat(a.getNombreVisible()).as("check nombreVisible").isEqualTo(expected.getNombreVisible()))
            .satisfies(a -> assertThat(a.getBio()).as("check bio").isEqualTo(expected.getBio()))
            .satisfies(a -> assertThat(a.getGithub()).as("check github").isEqualTo(expected.getGithub()))
            .satisfies(a -> assertThat(a.getWebPersonal()).as("check webPersonal").isEqualTo(expected.getWebPersonal()))
            .satisfies(a -> assertThat(a.getAvatarUrl()).as("check avatarUrl").isEqualTo(expected.getAvatarUrl()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerfilUsuarioUpdatableRelationshipsEquals(PerfilUsuario expected, PerfilUsuario actual) {
        // empty method
    }
}
