package com.haroun.bugoverflow.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProyectoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProyectoAllPropertiesEquals(Proyecto expected, Proyecto actual) {
        assertProyectoAutoGeneratedPropertiesEquals(expected, actual);
        assertProyectoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProyectoAllUpdatablePropertiesEquals(Proyecto expected, Proyecto actual) {
        assertProyectoUpdatableFieldsEquals(expected, actual);
        assertProyectoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProyectoAutoGeneratedPropertiesEquals(Proyecto expected, Proyecto actual) {
        assertThat(actual)
            .as("Verify Proyecto auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProyectoUpdatableFieldsEquals(Proyecto expected, Proyecto actual) {
        assertThat(actual)
            .as("Verify Proyecto relevant properties")
            .satisfies(a -> assertThat(a.getTitulo()).as("check titulo").isEqualTo(expected.getTitulo()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getUrlrepo()).as("check urlrepo").isEqualTo(expected.getUrlrepo()))
            .satisfies(a -> assertThat(a.getCategoria()).as("check categoria").isEqualTo(expected.getCategoria()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProyectoUpdatableRelationshipsEquals(Proyecto expected, Proyecto actual) {
        // empty method
    }
}
